services:
  okd-ui:
    # build: .
    image: okd-deployment-app
    ports:
      - "5000:5000"
    environment:
      - AUTH0_DOMAIN=
      - API_IDENTIFIER=
      - AUTH0_NAMESPACE=
      - OKD_CLUSTER_API=
      - OKD_SERVICE_ACCOUNT_TOKEN=
      - ADMIN_ROLE_NAME=
